id: https://w3id.org/linkml-common/environmental
name: linkml-common-environmental
title: linkml-common-environmental
description: |-
  Common Data Model Elements
license: MIT
see_also:
  - https://linkml.github.io/linkml-common

prefixes:
  linkml_common: https://w3id.org/linkml-common/
  linkml: https://w3id.org/linkml/
  biolink: https://w3id.org/biolink/
  schema: http://schema.org/
  ENVO: http://purl.obolibrary.org/obo/ENVO_
  fhir: http://hl7.org/fhir/
default_prefix: linkml_common
default_range: string

imports:
  - linkml:types
  - core
  - quantities
  - geography
  - investigations

classes:

  EnvironmentalSite:
    description: A location or site that is the subject of environmental monitoring
    is_a: Place

  EnvironmentalSystem:
    is_a: PhysicalSystem

  Climate:
    is_a: EnvironmentalSystem

  ClimateModel:
    is_a: Simulation
    slot_usage:
      models:
        range: Climate

  #EnvironmentalProcess:
  #  comments:
  #    - TODO
  #  #is_a: Process

  #EnvironmentalMonitoring:
  #  is_a: EnvironmentalProcess
